name: 'Wrangler-Preview'

on:
  pull_request:

permissions:
  contents: read

jobs:
  wrangler-preview:
    name: 'wrangler-preview'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM Install
        run: npm install

      - name: wrangler
        run: npx wrangler versions upload --tag "${{ github.event.pull_request.number }}" --message "${{ github.event.pull_request.title }}" --preview-alias "${{ github.head_ref }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
