name: 'Wrangler-Deploy'

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  deploy:
    name: 'deploy-preview'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM Install
        run: npm install

      - name: wrangler
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
